### ISSUE TITLE
Gets a nonzero liberal p-value when a zero is expected

### ISSUE THREAD

**Issue by HeidiChristensen** [myllym/GET#1]
When using 'rank_envelope' where the data curve has rank 1, I would expect to get a liberal p-value of 0 (according to expression (10) in 'Global envelope tests for spatial processes' (2017)). However, the p-interval returned from 'rank_envelope' gives a liberal p-value of 1/nsim instead.

**Comment by myllym** [comment]
Thank you for reporting this! There was indeed a slight difference in the p-value calculation. I have now updated the p-value calculations to correspond to the formulas in the 'Global envelope tests for spatial processes' (2017) paper.

**Comment by myllym** [comment]
I note that the liberal p-value calculation had (obviously accidentally) changed in an update of the p-value calculation code. It was originally the one from 'Global envelope tests for spatial processes' (2017), and as it has been corrected back to it, I am closing this issue now. Thanks again for HeidiChristensen for reporting!
