### ISSUE TITLE
Plotting of 2d envelopes broken for non-square matrices

### ISSUE THREAD

**Issue by antiphon** [myllym/GET#2]
I get an 
```
Error in spatstat::im(x$obs < x$lo, xcol = x$rx, yrow = x$ry) : 
  Length of xcol does not match ncol(mat)
```
This is due to the used `spatstat::im` and `spatstat::as.im` treating input x- and y-arguments differently. Plot using the latter are produced first and show up, but the code halts when the former is called.

Code to reproduce:

```
obs <- matrix(runif(110), 10, 11)
sims <- array(runif(110*12), c(12,10,11))
cr <- global_envelope_test_2d(obs, sims, 1:10, 1:11)
plot(cr)
```

https://github.com/myllym/GET/blob/136c08c940979040aad47770f9b6d49308355324/R/envelopes2d.r#L254

**Comment by myllym** [comment]
Thank you for reporting the error. The 2d envelope has gone through also some other updates now and the new corresponding code to reproduce is: 
`obs <- matrix(runif(110), 10, 11)`
`sims <- array(runif(110*12), c(10,11,12))`
i.e. the third dimension should match the number of functions, and
`iset <- create_image_set(list(r=list(1:10, 1:11), obs=obs, sim_m=sims))`
`cr <- global_envelope_test2d(iset)`
`plot(cr)`
