### ISSUE TITLE
Two-level, one-way contrast and ordering of levels

### ISSUE THREAD

**Issue by jmhrrsn** [myllym/GET#3]
Hi,

I am evaluating some data that contains two-level factors, and ran a `graph.flm()` test with `contrasts=TRUE`. The result is roughly what I expect, having previously analyzed this data with the `fda` package (but switching to GET in order to do tests that control for covariates), however the curve is upside down.

My factor has a natural treatment/no-treatment interpretation (labeled 1 and 0 in my dataframe, respectively) so I expected the "baseline" to be subtracted from the treatment when looking at the contrast, but the opposite is being done. Is there any way to force the ordering of the contrast? I have tried relabeling my factor in case it was alphabetical, but without success.

I have resorted to modifying the result object by multiplying `obs`, `central`, `lo` and `hi` by -1 and then swapping `lo` and `hi`, which seems to give me what I would expect, and I think should be correct. Do you have another recommendation?

Also, this was made slightly more confusing by the fact that with only a single variable omitted in the reduced model, the resulting graph is not titled, so it's not possible to determine which way around the contrast was done without running a second test with more categorical factors omitted, in which case the subplots are labeled and I was able to confirm my suspicion. Is there a way to force a plot label when there is only one plot, or otherwise determine which direction the contrast was done?

Thank you in advance and thank you for making this software available!

**Comment by myllym** [comment]
Thank you for your comment and interest! At the moment, the contrasts are indeed hard-coded to the specific style, but I will think about the possibility to allow the user to set them. 

I am sorry for the missing information about the order in the default title when there is only one plot/comparison. If your test output is saved in an R object res, you can find the title that you would like to have in attr(res, "labels").

**Comment by jmhrrsn** [comment]
Thank you for the quick response! 

Just to confirm: am I correct in thinking that multiplying obs, central, hi and lo by -1 and then exchanging lo and hi will give me the result I would have gotten if the contrast were done in the other direction?

**Comment by myllym** [comment]
I realise it can be a bit confusing with the different contrasts. In graph.flm, first, to obtain the regression coefficients for each group, the constrasts option "contr.sum" is used for the lm function. If you use `contrasts = FALSE` , the coefficients are used as the test statistic as such. If you use `constrasts = TRUE`, then differences of the coefficients are used as the test statistic. Given the coefficients in a specific order that is obtained through the use of lm and dummy.coef, the differences are taken currently by checking only couples i and j where i < j and reducing j from i. E.g. groups 1, 2, 3 leads to comparisons 1-2, 1-3, 2-3. I hope this clarifies.

**Comment by jmhrrsn** [comment]
Thank you! For others' reference, the workaround I discovered based on your explanation was to relevel my factor with the treatment condition as the reference level.

**Comment by myllym** [comment]
Hi, 
this took some time, but now the function `graph.flm` has a further option `NULL` for the argument `contrasts`. If `contrasts = NULL` the coefficients given by `lm` are used directly as the test statistic. (The contrasts of `lm` can be controlled by `options`.)
-Mari
