### ISSUE TITLE
nestedness checking and equivalent interactions when omitting a main effect

### ISSUE THREAD

**Issue by jmhrrsn** [myllym/GET#5]
When testing the significance of a variable that participates in interactions on its own, R seems to canonicalize the name of interaction terms differently, causing nestedness checks done by GET to fail:

```
library('GET')
library('fda.usc')

Y <- fdata(matrix(rnorm(96 * 120), 120, 96))
R <- fdata(matrix(rnorm(96 * 120), 120, 96))
S <- fdata(matrix(rnorm(96 * 120), 120, 96))
T <- fdata(matrix(rnorm(96 * 120), 120, 96))

data <- data.frame(V=as.factor(runif(120) > 0.5))
result <- graph.flm(50,
                    Y ~ V + R + S + T + V:S + V:T,
                    Y ~ R + S + T + V:S + V:T,
                    factors=data,
                    contrasts=TRUE,
                    curve_sets=list(Y=Y, Z=Z))
```

results in

```
Error in check_isnested(formula.full, formula.reduced): The reduced model includes some extra variables, not in the full model.
Traceback:

1. graph.flm(50, Y ~ V + R + S + T + V:S + V:T, Y ~ R + S + T + 
 .     V:S + V:T, factors = data, contrasts = TRUE, savefuns = TRUE, 
 .     curve_sets = list(Y = Y, Z = Z))
2. flm.checks(nsim = nsim, formula.full = formula.full, formula.reduced = formula.reduced, 
 .     curve_sets = curve_sets, factors = factors, fast = fast)
3. check_isnested(formula.full, formula.reduced)
4. stop("The reduced model includes some extra variables, not in the full model.")
```

This appears to be happening because the labels for the terms in the formula are `V:S` and `V:T` in the first formula but are computed as `S:V` and `T:V` in the reduced formula. A workaround for this is to add `V` to the full formula last.

**Comment by myllym** [comment]
Very interesting observation that relates to the behavior of the function terms. We will think about alternative ways to treat the terms. For interest, do you have some true case where testing the main effect (of V) when interaction effects is a relevant one?

**Comment by myllym** [comment]
We have changed to check the terms of the formulas by looking at the attribute `factors` given by `terms` rather than the labels. This should be generally a better solution. Thanks to @jmhrrsn for noting and thanks to @mikkoku for the help on implementation!
