### ISSUE TITLE
central_region always uses mean and never median as central function (at least in some cases). 

### ISSUE THREAD

**Issue by samperochkin** [myllym/GET#6]
When I set the `central` argument of `central_region` equal to `"median"`, it still uses `mean` as central function. I believe this is because the argument `central` of `get_T_0` is not specified when it is called inside `individual_central_region`. 

https://github.com/myllym/GET/blob/dfd7b0133d0052c694f61c66b9dd03f001b2a95c/R/envelopes.r#L125

More details : my actual call looks like `central_region(my_curve_set, type="erl", coverage=.8, central = "median")`.

**Comment by myllym** [comment]
Thank you so much for finding and reporting! This should be fixed now.
